apiVersion: v1
kind: Namespace
metadata:
  name: desk-reservation-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-nodejs
  namespace: desk-reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-nodejs
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "nodejs-instrumentation"
      labels:
        app: bff-nodejs
    spec:
      containers:
      - name: bff-nodejs
        image: gzarba/desk-reservation-app:bff-nodejs
        ports:
        - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: bff-nodejs
  namespace: desk-reservation-app
spec:
  selector:
    app: bff-nodejs
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002