apiVersion: v1
kind: Namespace
metadata:
  name: desk-reservation-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-nodejs
  namespace: desk-reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-nodejs
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "nodejs-instrumentation"
      labels:
        app: bff-nodejs
    spec:
      containers:
      - name: bff-nodejs
        image: gzarba/desk-reservation-app:bff-nodejs
        imagePullPolicy: Always
        ports:
        - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: bff-nodejs
  namespace: desk-reservation-app
spec:
  selector:
    app: bff-nodejs
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-nodejs-ingress
  namespace: desk-reservation-app
  labels:
    name: bff-nodejs-ingress
spec:
  rules:
  - host: bff-desk-reservation-app.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bff-nodejs
            port: 
              number: 3002

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bff-nodejs-hpa
  namespace: desk-reservation-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bff-nodejs
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
    type: Resource
  - resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
    type: Resource